config/routes.rb
Sigma::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "add" => "beliefs#add", :as => "add"

  root :to => 'home#index'

  get "home/add_beliefs"
  get "home/sample"
  get "home/display", :as => "display"
  get "beliefs/existing"

  resources :beliefs

  resources :users
  resources :sessions

end

app/models/belief.rb
class Belief < Neo4j::Rails::Model
  index :title
  property :title, :type => String
  validates :title, :uniqueness => true
  property :description, :type => String
  
  #has_n(:users)
  #has_n(:related_beliefs).to(Belief).relationship(Connection)
  #has_n(:rel_beliefs).from(Belief, :related_beliefs)
  
  #has_n(:peer, :type=> Belef)
  #has_n(:denpendencies)
  #has_n(:dependents)

  public

  def self.generate_beliefs (belief_count)
    beliefs=Array.new { }
    for i in 0..belief_count-1
      beliefs[i] = "b#{i}"
    end
    return beliefs
  end

end

app/controllers/beliefs_controller.rb
class BeliefsController < ApplicationController
  # GET /beliefs
  # GET /beliefs.json
  def index
    @beliefs = current_user.beliefs

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @beliefs }
    end
  end

  # GET /beliefs/1
  # GET /beliefs/1.json
  def show
    @belief = Belief.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @belief }
    end
  end

  # GET /beliefs/new
  # GET /beliefs/new.json
  def new
    @belief = Belief.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @belief }
    end
  end

  # GET /beliefs/1/edit
  def edit
    @belief = Belief.find(params[:id])
  end

  # POST /beliefs
  # POST /beliefs.json
  def create
    if(current_user.id)
      @belief = Belief.find_by_title(params[:title]) 
      
      if @belief == nil
        @belief = Belief.new(params[:belief])
        current_user.beliefs << @belief
        @belief.users << current_user
        current_user.update
      
        respond_to do |format|
          if @belief.save
            format.html { redirect_to @belief, :notice => 'Belief was successfully created.' }
            format.json { render :json => @belief, :status => :created, :location => @belief }
          else
            format.html { render :action => "new" }
            format.json { render :json => @belief.errors, :status => :unprocessable_entity }
          end
        end
      else
        format.html { render :action => "new", :notice => 'Please Log in.' }
      end
      
      else
        #@belief.errors << "Please go to page to add existing belief"
        respond_to do |format|
          format.html { render :action => "new" }
          format.json { render :json => @belief.errors, :status => :unprocessable_entity }
        end
      end
  end

  # PUT /beliefs/1
  # PUT /beliefs/1.json
  def update
    @belief = Belief.find(params[:id])

    respond_to do |format|
      if @belief.update_attributes(params[:belief])
        format.html { redirect_to @belief, :notice => 'Belief was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @belief.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /beliefs/1
  # DELETE /beliefs/1.json
  def destroy
    @belief = Belief.find(params[:id])
    @belief.destroy

    respond_to do |format|
      format.html { redirect_to beliefs_url }
      format.json { head :no_content }
    end
  end
  
  def existing
     @beliefs = Belief.all
     #@non_beliefs = current_user.beliefs
     
     # Beliefs you don't hold
     #@beliefs = @beliefs - @non_beliefs
  end
  
  def add
     @belief = Belief.find(params[:id])
     current_user.beliefs << @belief
     

     respond_to do |format|
       if @belief.update
         format.html { redirect_to @belief, :notice => 'Belief was successfully added.' }
         format.json { head :no_content }
       else
         format.html { render :action => "edit" }
         format.json { render :json => @belief.errors, :status => :unprocessable_entity }
       end
     end
   end
end

app/helpers/beliefs_helper.rb
module BeliefsHelper
   def self.generate_beliefs (belief_count)
    beliefs=Array.new { }
    for i in 0..belief_count-1
      beliefs[i] = "b#{i}"
    end
    return beliefs
  end
end

app/views/beliefs/_form.html.erb
<%= form_for(@belief) do |f| %>
  <% if @belief.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@belief.errors.count, "error") %> prohibited this belief from being saved:</h2>

      <ul>
      <% @belief.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beliefs/edit.html.erb
<h1>Editing belief</h1>

<%= render 'form' %>

<%= link_to 'Show', @belief %> |
<%= link_to 'Back', beliefs_path %>

app/views/beliefs/existing.html.erb
<h1>All beliefs you don't hold</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @beliefs.each do |belief| %>
  <tr>
    <td><%= belief.title %></td>
    <td><%= belief.description %></td>
    <td><%= link_to 'Add', belief, :method => :add %></td
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Belief', new_belief_path %>

app/views/beliefs/index.html.erb
<h1>Listing beliefs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @beliefs.each do |belief| %>
  <tr>
    <td><%= belief.title %></td>
    <td><%= belief.description %></td>
    <td><%= link_to 'Show', belief %></td>
    <td><%= link_to 'Edit', edit_belief_path(belief) %></td>
    <td><%= link_to 'Destroy', belief, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Belief', new_belief_path %>

app/views/beliefs/new.html.erb
<h1>New belief</h1>

<%= render 'form' %>

<%= link_to 'Back', beliefs_path %>

app/views/beliefs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @belief.title %>
</p>

<p>
  <b>Description:</b>
  <%= @belief.description %>
</p>


<%= link_to 'Edit', edit_belief_path(@belief) %> |
<%= link_to 'Back', beliefs_path %>